@startuml

actor Usuario

participant Producto
participant TipoProducto

Usuario -> Producto : seleccionarProducto()

Producto -> TipoProducto : asignarTipoProducto()

TipoProducto --> Producto : tipo asignado

Producto --> Usuario : confirmación

@enduml